routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/cek', function () {
    return view('layouts.theme');
});


Route::resource('akun', 'AkunController');

Route::resource('pelanggan', 'PelanggansController');

Route::resource('supplier', 'SuppliersController');

Route::resource('produk', 'ProduksController');

Route::resource('aset', 'AsetsController');

Route::get('/kasbank', 'KasBankController@index')->name('kasbank');

Route::resource('transfer', 'TransferBankController');

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    protected $fillable = ['nama_perusahaan', 'nama_pemilik', 'nama_panggilan', 'alamat_penagihan', 'telpon', 'email', 'npwp', 'informasi_lain', 'akun_piutang_id', 'akun_hutang_id'];
}

app/Http/Controllers/SuppliersController.php
<?php

namespace App\Http\Controllers;

use App\Supplier;
use App\Akun;
use Illuminate\Http\Request;

class SuppliersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $suppliers = Supplier::all();
        return view('supplier.index', compact('suppliers'));
    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $akuns = Akun::all();
        return view('supplier.tambah', compact('akuns'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_panggilan' => 'required',
        ]);

        $akun = Supplier::create([
            'nama_perusahaan' => request('nama_perusahaan'),
            'nama_pemilik' => request('nama_pemilik'),
            'nama_panggilan' => request('nama_panggilan'),
            'alamat_penagihan' => request('alamat_penagihan'),
            'telpon' => request('telpon'),
            'email' => request('email'),
            'npwp' => request('npwp'),
            'informasi_lain' => request('informasi_lain'),
            'akun_hutang_id' => request('akun_hutang_id'),
            'akun_piutang_id' => request('akun_piutang_id'),
       ]);
        // $request->akun()->create($request->only('kode_akun', 'nama_akun', 'detail_akun', 'kategori_akun_id'));
        
        return redirect()->route('supplier.index')->with('success', 'Data supplier telah tersimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function show(Supplier $supplier)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function edit(Supplier $supplier)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Supplier $supplier)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function destroy(Supplier $supplier)
    {
        //
    }
}

resources/views/supplier/index.blade.php
@extends('layouts.theme')

@section('content')
@include('layouts._messages')
<div class="box">
    <div class="box-header">
        <h3 class="box-title">Data Supplier</h3>
        <a href="{{ route('supplier.create') }}" class="btn btn-primary pull-right">
        <span class="fa  fa-plus-square"></span>        
        Tambah Supplier</a>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Nama Panggilan</th>
                    <th>Alamat</th>
                    <th>Email</th>
                    <th>Telepon</th>
                    <th>Saldo</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($suppliers as $supplier)
                <tr>
                    <td>{{ $supplier->nama_panggilan}}</td>
                    <td>{{ $supplier->alamat_penagihan }}</td>
                    <td>{{ $supplier->email }}</td>
                    <td>{{ $supplier->telpon }}</td>
                    <td>0.00</td>
                </tr>
                @endforeach
            </tbody>

        </table>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->
@endsection

resources/views/supplier/tambah.blade.php
@extends('layouts.theme')

@section('content')
<div class="col-md-12">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">{{ __('Tambah Supplier') }}</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form method="POST" class="form-horizontal" action="{{ route('supplier.store') }}">
            @csrf
            <div class="box-body">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="nama_perusahaan" class="col-sm-4 col-form-label text-md-right">Nama Perusahaan</label>

                        <div class="col-md-6">
                            <input id="nama_perusahaan" type="text" class="form-control{{ $errors->has('nama_perusahaan') ? ' is-invalid' : '' }}"
                                name="nama_perusahaan" value="{{ old('nama_perusahaan') }}" autofocus>
                        </div>

                    </div>
                    <div class="form-group">
                        <label for="nama_pemilik" class="col-md-4 col-form-label text-md-right">Nama pemilik</label>

                        <div class="col-md-6">
                            <input id="nama_pemilik" type="text" class="form-control{{ $errors->has('nama_pemilik') ? ' is-invalid' : '' }}"
                                name="nama_pemilik" value="{{ old('nama_pemilik') }}" >

                        </div>
                    </div>

                    <div class="form-group">
                        <label for="nama_panggilan" class="col-md-4 col-form-label text-md-right">Nama Panggilan *</label>

                        <div class="col-md-6">
                            <input id="nama_panggilan" type="text" class="form-control{{ $errors->has('nama_panggilan') ? ' is-invalid' : '' }}"
                                name="nama_panggilan" value="{{ old('nama_panggilan') }}" required>

                        </div>
                    </div>

                    <div class="form-group">
                        <label for="alamat_penagihan" class="col-md-4 col-form-label text-md-right">Alamat Penagihan</label>

                        <div class="col-md-6">
                            <textarea id="alamat_penagihan" class="form-control{{ $errors->has('alamat_penagihan') ? ' is-invalid' : '' }}"
                                rows="4" name="alamat_penagihan" > {{ old('alamat_penagihan') }} </textarea>

                        </div>
                    </div>                 

                    <!-- coment here -->
                </div>

                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="telpon" class="col-sm-4 col-form-label text-md-right">Telpon</label>

                        <div class="col-md-6">
                            <input id="telpon" type="text" class="form-control{{ $errors->has('telponl') ? ' is-invalid' : '' }}"
                                name="telpon" value="{{ old('telpon') }}" >
                        </div>

                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-sm-4 col-form-label text-md-right">Email</label>

                        <div class="col-md-6">
                            <input id="email" type="text" class="form-control{{ $errors->has('emaill') ? ' is-invalid' : '' }}"
                                name="email" value="{{ old('email') }}" s>
                        </div>

                    </div>

                    <div class="form-group row">
                        <label for="npwp" class="col-sm-4 col-form-label text-md-right">NPWP</label>

                        <div class="col-md-6">
                            <input id="npwp" type="text" class="form-control{{ $errors->has('npwpl') ? ' is-invalid' : '' }}"
                                name="npwp" value="{{ old('npwp') }}" >
                        </div>

                    </div>

                    <div class="form-group">
                        <label for="informasi_lain" class="col-md-4 col-form-label text-md-right">Informasi Lainnya</label>

                        <div class="col-md-6">
                            <textarea id="informasi_lain" class="form-control{{ $errors->has('informasi_lain') ? ' is-invalid' : '' }}"
                                rows="4" name="informasi_lain"> {{ old('informasi_lain') }} </textarea>

                        </div>

                    </div>

                    <div class="form-group">
                            <label for="akun_piutang_id" class="col-md-4 col-form-label text-md-right">Akun Piutang</label>
    
                            <div class="col-md-6">
                                <select id="akun_piutang_id" name="akun_piutang_id" class="form-control select2" style="width: 100%;">
                                    @foreach ($akuns as $akun)
                                    <option value="{{ $akun->id }}">{{ $akun->nama_akun}}</option>
    
                                    @endforeach
    
                                </select>
    
                            </div>
                        </div>

                        <div class="form-group">
                                <label for="akun_hutang_id" class="col-md-4 col-form-label text-md-right">Akun Hutang</label>
        
                                <div class="col-md-6">
                                    <select id="akun_hutang_id" name="akun_hutang_id" class="form-control select2" style="width: 100%;">
                                        @foreach ($akuns as $akun)
                                        <option value="{{ $akun->id }}">{{ $akun->nama_akun}}</option>
        
                                        @endforeach
        
                                    </select>
        
                                </div>
                            </div>




                </div>

            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <div class="col-md-8 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        <span class="fa fa-plus"></span>
                        {{ __('Tambah') }}

                    </button>

                </div>
            </div>
            <!-- /.box-footer -->
        </form>
    </div>
    <!-- /.box -->
</div>

@endsection