routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/cek', function () {
    return view('layouts.theme');
});


Route::resource('akun', 'AkunController');

Route::resource('pelanggan', 'PelanggansController');

Route::resource('supplier', 'SuppliersController');

Route::resource('produk', 'ProduksController');

Route::resource('aset', 'AsetsController');

Route::get('/kasbank', 'KasBankController@index')->name('kasbank');

Route::resource('transfer', 'TransferBankController');

app/Aset.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Aset extends Model
{
    protected $fillable = ['kode', 'nama', 'akun_aset_id', 'deskripsi', 'tanggal_akuisisi', 'biaya_akuisisi', 'akun_kredit_id'];

    public function akun_aset()
    {
        return $this->belongsTo(Akun::class, 'akun_aset_id');
    }
}

app/Http/Controllers/AsetsController.php
<?php

namespace App\Http\Controllers;

use App\Aset;
use App\Akun;
use Illuminate\Http\Request;

class AsetsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $asets = Aset::all();

      // print_r($akuns);
       return view('aset.index', compact('asets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $akuns = Akun::all();
        return view('aset.tambah', compact('akuns'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $aset = Aset::create([
            'kode' => request('kode'),
            'nama' => request('nama'),
            'akun_aset_id' => request('akun_aset_id'),
            'deskripsi' => request('deskripsi'),
            'tanggal_akuisisi' => request('tanggal_akuisisi'),
            'biaya_akuisisi' => request('biaya_akuisisi'),
            'akun_kredit_id' => request('akun_kredit_id'),

       ]);
        // $request->akun()->create($request->only('kode_akun', 'nama_akun', 'detail_akun', 'kategori_akun_id'));
        
        return redirect()->route('aset.index')->with('success', 'Data aset telah tersimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Aset  $aset
     * @return \Illuminate\Http\Response
     */
    public function show(Aset $aset)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Aset  $aset
     * @return \Illuminate\Http\Response
     */
    public function edit(Aset $aset)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Aset  $aset
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Aset $aset)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Aset  $aset
     * @return \Illuminate\Http\Response
     */
    public function destroy(Aset $aset)
    {
        //
    }
}

resources/views/aset/index.blade.php
@extends('layouts.theme')

@section('content')
@include('layouts._messages')
<div class="box">
    <div class="box-header">
        <h3 class="box-title">Data Aset</h3>
        <a href="{{ route('aset.create') }}" class="btn btn-primary pull-right">
        <span class="fa fa-plus-square"></span>        
        Tambah Aset</a>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Tanggal Akuisisi</th>
                    <th>Detail Aset</th>
                    <th>Akun Aset</th>
                    <th>Biaya Akuisisi</th>
                    <th>Nilai Baku</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($asets as $aset)
                <tr>
                    <td>{{ $aset->tanggal_akuisisi }}</td>
                    <td>{{ $aset->nama}}</td>
                    <td>{{ $aset->akun_aset->nama_akun}}</td>
                    <td>{{ $aset->biaya_akuisisi}}</td>
                    <td>{{ $aset->biaya_akuisisi}}</td>
                </tr>
                @endforeach
            </tbody>

        </table>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->
@endsection

resources/views/aset/tambah.blade.php
@extends('layouts.theme')

@section('content')
<div class="col-md-12">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">{{ __('Tambah Aset') }}</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form method="POST" class="form-horizontal" action="{{ route('aset.store') }}">
            @csrf
            <div class="box-body">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="kode" class="col-sm-4 col-form-label text-md-right">Kode Aset</label>

                        <div class="col-md-6">
                            <input id="kode" type="text" class="form-control{{ $errors->has('kode') ? ' is-invalid' : '' }}"
                                name="kode" value="{{ old('kode') }}" autofocus>
                        </div>

                    </div>

                    <div class="form-group row">
                        <label for="nama" class="col-sm-4 col-form-label text-md-right">Nama Aset</label>

                        <div class="col-md-6">
                            <input id="nama" type="text" class="form-control{{ $errors->has('nama') ? ' is-invalid' : '' }}"
                                name="nama" value="{{ old('nama') }}" autofocus>
                        </div>

                    </div>

                    <div class="form-group">
                        <label for="akun_aset_id" class="col-md-4 col-form-label text-md-right">Akun Aset Tetap</label>

                        <div class="col-md-6">
                            <select id="akun_aset_id" name="akun_aset_id" class="form-control select2" style="width: 100%;">
                                @foreach ($akuns as $akun)
                                <option value="{{ $akun->id }}">{{ $akun->nama_akun}}</option>

                                @endforeach

                            </select>

                        </div>
                    </div>

                    <div class="form-group">
                        <label for="deskripsi" class="col-md-4 col-form-label text-md-right">Deskripsi</label>

                        <div class="col-md-6">
                            <textarea id="deskripsi" class="form-control{{ $errors->has('deskripsi') ? ' is-invalid' : '' }}"
                                rows="4" name="deskripsi"> {{ old('deskripsi') }} </textarea>
                        </div>
                    </div>

                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="tanggal_akuisisi" class="col-md-4 col-form-label text-md-right">Tanggal Akuisisi</label>

                        <div class="col-md-6">
                            <input id="tanggal_akuisisi" type="date" class="form-control{{ $errors->has('tanggal_akuisisi') ? ' is-invalid' : '' }}"
                                name="tanggal_akuisisi" value="{{ old('tanggal_akuisisi') }}">
                        </div>
                    </div>

                    

                    <div class="form-group">
                        <label for="biaya_akuisisi" class="col-md-4 col-form-label text-md-right">Biaya Akuisisi</label>

                        <div class="col-md-6">
                            <input id="biaya_akuisisi" type="text" class="form-control{{ $errors->has('biaya_akuisisi') ? ' is-invalid' : '' }}"
                                name="biaya_akuisisi" value="{{ old('biaya_akuisisi') }}" required>
                        </div>
                    </div>

                    <div class="form-group">
                            <label for="akun_kredit_id" class="col-md-4 col-form-label text-md-right">Akun Dikreditkan</label>
    
                            <div class="col-md-6">
                                <select id="akun_kredit_id" name="akun_kredit_id" class="form-control select2" style="width: 100%;">
                                    @foreach ($akuns as $akun)
                                    <option value="{{ $akun->id }}">{{ $akun->nama_akun}}</option>
    
                                    @endforeach
    
                                </select>
    
                            </div>
                        </div>

                   
                    <!-- coment here -->
                </div>
            </div>
            

            <div class="box-footer">
                <div class="col-md-8 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        <span class="fa fa-plus"></span>
                        {{ __('Tambah') }}

                    </button>

                </div>
            </div>
            <!-- /.box-footer -->
        </form>
    </div>
    <!-- /.box -->
</div>

@endsection